packages:
  - "packages/*"
  - "apps/*"

overrides:
  yaml@<2.8.3: ">=2.8.3 <3.0.0"
  js-yaml@<=4.1.1: "4.2.0"
  read-yaml-file>js-yaml: 3.14.2
  esbuild: 0.28.1

onlyBuiltDependencies:
  - esbuild
  - sharp
