// Per-page OG cards, rendered at build time from the shared template in
// src/shared/og-card.mjs. Every docs entry gets /og/<entry-id>.png (the docs
// content collection already ids entries as "docs", "docs/guides/prompt", …)
// plus a card for the playground. The home page keeps the committed
// public/og-image.png generated by scripts/build-og-image.mjs.
import type { APIRoute } from "astro";
import { getCollection } from "astro:content";
import { renderOgCardPng } from "../../shared/og-card.mjs";

// Hand-written card taglines, one line each. Frontmatter descriptions are
// tuned for SERPs and run long, and a truncated line reads badly at card
// scale — so every page gets a static line sized to fit unclipped.
const TAGLINES: Record<string, string> = {
  docs: "TypeScript lifecycle wrappers for the browser's built-in AI APIs.",
  "docs/architecture": "One package per browser capability, zero runtime dependencies.",
  "docs/browser-support": "Current Chrome and Edge support for every package.",
  "docs/production-checklist": "Input, sessions, safe output, user control, progress, and caches.",
  "docs/why-web-ai-sdk": "How it differs from server-side model-provider SDKs.",
  "docs/guides/prompt": "One-shot prompts and multi-turn sessions with LanguageModel.",
  "docs/guides/summarizer": "Summarize on-device with streaming and session reuse.",
  "docs/guides/translator": "Translate on-device with streaming and pair-based sessions.",
  "docs/guides/detector": "Detect text language with confidence scores, on-device.",
  "docs/guides/writer": "Generate text on-device with streaming and session reuse.",
  "docs/guides/rewriter": "Revise tone and length on-device with streaming.",
  "docs/guides/proofreader": "Correct grammar and spelling, and inspect each fix.",
  "docs/guides/webmcp": "Register and execute agent-callable tools in the browser.",
  "docs/guides/session-lifecycle": "Prepare sessions on intent, reuse them, release them.",
  "docs/guides/meta-package": "One install, all eight building blocks.",
  "docs/packages/all": "Every wrapper behind a single dependency.",
  "docs/packages/prompt": "The built-in Prompt API with lifecycle, streaming, and aborts.",
  "docs/packages/summarizer": "The built-in Summarizer API with streaming and caching.",
  "docs/packages/translator": "The built-in Translator API with pair-cached sessions.",
  "docs/packages/detector": "The built-in Language Detector API with confidence scores.",
  "docs/packages/writer": "The built-in Writer API with streaming and session reuse.",
  "docs/packages/rewriter": "The built-in Rewriter API with streaming and session reuse.",
  "docs/packages/proofreader": "The built-in Proofreader API with per-issue corrections.",
  "docs/packages/webmcp": "The W3C WebMCP API at document.modelContext.",
  "docs/react/use-prompt": "React adapter for prompts with a full state machine.",
  "docs/react/use-session": "Lifecycle-only React adapter for LanguageModel sessions.",
  "docs/react/use-summarizer": "React adapter for on-device summarization.",
  "docs/react/use-translator": "React adapter for on-device translation.",
  "docs/react/use-detector": "React adapter for on-device language detection.",
  "docs/react/use-writer": "React adapter for on-device text generation.",
  "docs/react/use-rewriter": "React adapter for on-device rewriting.",
  "docs/react/use-proofreader": "React adapter for on-device proofreading.",
  "docs/react/use-webmcp": "Register and read WebMCP tools from one React hook.",
};

// Install command per page. Capability pages (package, guide, or React hook)
// advertise their own package; overview pages keep the meta-package like the
// home card. Unmapped future pages fall back to the capability inferred from
// the id, then to the meta-package.
const CAPABILITIES = [
  "prompt",
  "summarizer",
  "translator",
  "detector",
  "writer",
  "rewriter",
  "proofreader",
  "webmcp",
] as const;

function installFor(id: string): string {
  const pkg = id.match(/^docs\/packages\/([a-z-]+)$/)?.[1];
  if (pkg) return `@web-ai-sdk/${pkg}`;
  if (id === "docs/guides/session-lifecycle" || id === "docs/react/use-session")
    return "@web-ai-sdk/prompt";
  const tail = id.split("/").pop() ?? "";
  const capability = CAPABILITIES.find(
    (name) => tail === name || tail === `use-${name}`,
  );
  return capability ? `@web-ai-sdk/${capability}` : "@web-ai-sdk/all";
}

// New pages without a curated line fall back to a generic stamp rather than
// a truncated description; the warning keeps the map honest.
const FALLBACK_TAGLINE = "web-ai-sdk documentation.";

interface CardProps {
  eyebrow: string;
  title: string;
  tagline: string;
  install: string;
}

export async function getStaticPaths() {
  const docs = await getCollection("docs");
  const paths = docs.map((entry) => {
    const tagline = TAGLINES[entry.id];
    if (!tagline) {
      console.warn(
        `[og] no curated tagline for "${entry.id}" — using the generic fallback. Add one to TAGLINES in src/pages/og/[...slug].png.ts.`,
      );
    }
    return {
      params: { slug: entry.id },
      props: {
        eyebrow: "web-ai-sdk docs",
        title: entry.data.title,
        tagline: tagline ?? FALLBACK_TAGLINE,
        install: installFor(entry.id),
      } satisfies CardProps,
    };
  });

  paths.push({
    params: { slug: "playground" },
    props: {
      eyebrow: "web-ai-sdk playground",
      title: "Playground",
      tagline: "A fully on-device agent playground for the Web AI surface.",
      install: "@web-ai-sdk/all",
    } satisfies CardProps,
  });

  return paths;
}

export const GET: APIRoute<CardProps> = ({ props }) => {
  const png = renderOgCardPng({ ...props, caret: false });
  return new Response(new Uint8Array(png), {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=86400",
    },
  });
};
